SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO AS A
WHERE FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO AS B
    WHERE A.FOOD_TYPE = B.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;