SELECT A.APNT_NO, C.PT_NAME, A.PT_NO, A.MCDP_CD, B.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
JOIN DOCTOR AS B
ON A.MDDR_ID = B.DR_ID
JOIN PATIENT AS C
ON A.PT_NO = C.PT_NO
WHERE YEAR(A.APNT_YMD) LIKE 2022 AND MONTH(A.APNT_YMD) LIKE 4 AND DAY(A.APNT_YMD) LIKE 13 AND B.MCDP_CD LIKE 'CS' AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD;